version: "3"
volumes:
  news-db:


networks:
  newsbot-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16


services:
  news_extractor:
    restart: always
    image: astandre/cb_news_extractor
    container_name: cb_news_extractor
    ports:
      - "5000:8000"
    environment:
      - FB_TOKEN=
    links:
      - news-db
    depends_on:
      - news-db
    networks:
      - newsbot-net

  news-db:
    image: mysql
    container_name: news-db
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
    volumes:
      - news-db:/var/lib/mysql
    networks:
      - newsbot-net